firebug/rdp-inspector

- lib/main.js
This pr fix toolbox overlay unregistering which should happen on addon unload
> Fix unregister toolbox overlay on unload

- data/inspector/inspector.js
- data/inspector/packet-details.js
- data/inspector/packet-list.js
- data/inspector/packet.js
- data/inspector/packets-tab-body.js
- lib/inspector-window.js
This depends on the fix firebug/firebug.sdk#6 and refreshes the packet detail tree-view on packet selection (currently only the minimal changes to activate the feature, without any cleanup or css tweaks)
> Refresh packet-detail tree-view when a packet is selected in the packet-list

- data/inspector/components/main-tabbed-area.js
This pr puts into a comment the "not yet implemented" actors tab (just as a temporary workaround for the upcoming preview release) and remove the old (and commented out) tabs
> disable actors tab

- data/inspector/components/packets-sidebar.js
- data/inspector/components/tree-editor-view.js
This pr fix the "packet-editor reset on new selectedPacket or sidebar tab change" issues and in the process I've added the following new behaviour:
- when a new packet is selected in the packet list the sidebar switch automatically to the "Packet Detail tab"
> Fix "do not reset packet-editor on new selectedPacket or sidebar tab change"

- data/inspector/components/packet-editor.js
- data/inspector/components/packets-sidebar.js
- data/inspector/components/tree-editor-view.js
This pull request fixes indentation and add proper JS docs on the packet-editor and tree-editor-view modules.
(The real change is composed of the last two commits, but it's based on the #24, so I'm going to rebase it once #24 will be merged)
> Fix indentation and js docs on packet-editor and tree-editor-view modules

- data/inspector/components/packets-sidebar.js
This change only switch the sidebar to Packet Details only when a new packet is selected
Previously it did change to the Packet Details even when the selected packet was ```null``` or
```undefined```
> Fix "switch to sidebar to Packet Details only on new selected packet"

- data/inspector/components/packets-sidebar.js
This pull request fixes a couple of typos in the PacketsSidebar componentWillReceiveProps,
it should switch the sidebar to the PacketDetails only when a packet is selected.
(e.g. it should not switch to PacketDetails sidebar tab when we send a new Packet from the
PacketEditor sidebar tab)
> Fix typos in the PacketsSidebar componentWillReceiveProps

- chrome/locale/en-US/inspector.properties
- data/inspector/components/main-tabbed-area.js
- data/inspector/components/packets-toolbar.js
- data/inspector/main.js
- data/inspector/packets-store.js
- karma-tests/components/main-tabbed-area-spec.js
- karma-tests/components/packets-toolbar-spec.js
- karma.conf.js
- lib/inspector-window.js
This pull request (which will fix #22) adds a new File menu in the packets panel toolbar, the related save/load methods in the actions singleton and serialize/deserialize methods in the PacketsStore.
It renders a bootstrap based warning alert (auto dismissed within 2 seconds) on serializing/deserializing errors.
The two commits contain the karma unit tests which ensure the presence of the new packets panel toolbar menu and ensure the load/save actions are called when the user clicks on the corresponding menu items:
- https://travis-ci.org/rpl/rdp-inspector/builds/62935280#L287-L294
Follows a screencast of the feature:
> Feature: save and load packets store

- data/inspector/components/actors-toolbar.js
This pull request add a key property to the OPTION elements to fix the related react warnings.
> add key to select options in ActorsToolbar (fix #41)

- .eslintrc
- .travis.yml
- data/inspector/components/packet.js
- karma-tests/components/packet-spec.js
- karma.conf.js
- package.json
This pull request introduces:
- a small fix for #44 and related spec test (Packet React component should not render errorMessage if packet.error):
- https://github.com/firebug/rdp-inspector/compare/master...rpl:fix/44?expand=1#diff-7fc17a2eae531632ff955af7c212f748R108
- https://github.com/firebug/rdp-inspector/compare/master...rpl:fix/44?expand=1#diff-d204de2a6152530740205f7cdb2f02bfR51
- https://travis-ci.org/rpl/rdp-inspector#L546
- fix npm install issues related to es6 code coverage (change deprecated istanbul-harmony with isparta)
- enhance travis-ci build log with code coverage stats:
- https://travis-ci.org/rpl/rdp-inspector#L561
> Packet React component should not render errorMessage if packet.error is null

- .eslintrc
- data/inspector/components/packets-summary.js
- package.json
In this PR I'm experimenting usage of eslint plugins:
- [eslint-plugin-no-tabs](http://github.com/rpl/eslint-plugin-no-tabs) is a new minimal plugin which prevents any tab whitespace in the javascript sources (I've create this new plugin as a temporary replacement for the currently disabled 'indent' eslint rule)
- [eslint-plugin-react](https://github.com/rpl/eslint-plugin-react/tree/fix/displayName-and-propTypes-on-jsx-false) is a plugin with a bunch of useful linting rules related to React (I'm currently using my fork of the original repo because it didn't recognized all the components when jsx is not used, we can turn it into the standard one once the fix will be merged)
Then, with the **react/display-name** eslint rule active, I've found and fixed a missing displayName in a …
> add eslint-plugin-no-tabs and eslint-plugin-react

- chrome/locale/en-US/inspector.properties
- data/inspector/components/packets-toolbar.js
- data/inspector/css/toolbar.css
- karma-tests/components/packets-toolbar-spec.js
This PR (as a follow up of #40) turns the options inside PacketsPanel toolbar into checkbox menu items (to match the behaviour of the same options inside the start button menu popup)
> Turn options inside PacketsPanel toolbar into checkbox menu items

- data/inspector/components/main-tabbed-area.js
- data/inspector/components/packet-editor.js
- data/inspector/components/packet.js
- data/inspector/components/packets-panel.js
- data/inspector/components/packets-sidebar.js
- data/inspector/main.js
- karma-tests/components/packet-spec.js
- karma-tests/components/packets-sidebar-spec.js
- karma-tests/lib/firebug-sdk-shims.js
This PR reintroduces the "Edit and Resend Packet" feature (which will fix #45).
The new behaviour is:
- right-clicking on a *Sent* packet opens a context menu
- clicking on the *Edit and Resend* action from the context menu will:
- set the packet in the ```PacketEditor```
- switch the sidebar to the *Send Packet* tab 
(currently only if the edited packet is different from the previously edited packet)
Working on testing this feature I found an issue pointed out by a React warning which needs to be fixed in the firebug.sdk dependency (opened as PR firebug/firebug.sdk#8)
> Feature: "Edit and Resent" action in Packet context menu 

- data/inspector/components/packet.js
- data/inspector/components/packets-sidebar.js
- data/inspector/main.js
- karma-tests/components/packets-sidebar-spec.js
This PR introduces two small changes to polish the "Edit and Resend" feature from a User POV:
- ensure the sidebar will always be switched to the editor tab when the user click on the "Edit and Resend" action (currently by subscribing a custom "rdpinspector:switchToPacketEditorTab" DOM Event, which is not elegant from a React point of view and it should be changed once we change how we push the app state down in the React components tree)
- ensure the Packet context menu will be hidden on mouse leave (by positioning the context menu to ensure the mouse pointer is initially inside the opened context menu)
> Tweaks on packet context menu and auto-switching to packet editor sidebar tab 

- data/inspector/components/actors-panel.js
- data/inspector/components/factories.js
- data/inspector/components/packet-list.js
- data/inspector/components/pools.js
- package.json
This PR turns the Packets and Actors filtering into a case insensitive filtering.
I've tried to keep it as small as possible so we can include a fix to #37 in the upcoming 1.0.5 release.
In a follow up I'm going to introduce the new option to enable the optional "case sensitive" version, and I'm going to move the filtering in the packets and actors stores (which will help to simplify the React components which contains filter, and the stores is where the filtering should happen to keep this details out of the React components)
> Packets and Actors filtering should be case insensitive

- data/inspector/components/packet-list.js
- data/inspector/packets-store.js
Small follow up on #53, optimizing packets filtering by caching the raw RDP packet string.
> cache raw RDP packet string to optimize packets filtering

- .eslintrc
- data/inspector/components/packet-stack-sidepanel.js
- data/inspector/components/packet.js
- data/inspector/components/packets-summary.js
- data/inspector/components/stack-frame-rep.js
- data/inspector/packets-store.js
- karma-tests/components/main-tabbed-area-spec.js
- lib/inspector-service.js
- lib/toolbox-overlay.js
- lib/transport-observer.js
This PR introduces a couple of small changes to fix #42
- marks packets generated by our custom inspector actor (by adding a custom ```rdpInspectorInternals``` attributes to the replies)
- filters requests marked by ```rdpInspectorInternals``` attribute and their expected related replies (by actor id)
- filters actorInspector requests and replies (matching the actor prefix in the ```to```/```from```)
NOTE: this PR depends on firebug/firebug.sdk#9
> Filter out packets generated RDPi

- .eslintrc
- data/.eslintrc
- data/inspector/config.js
- data/inspector/main.js
- karma-tests/.eslintrc
- lib/.eslintrc
- lib/inspector-actor.js
- lib/inspector-front.js
- lib/inspector-service.js
- lib/inspector-window.js
- lib/main.js
- lib/start-button.js
- lib/toolbox-overlay.js
- lib/transport-observer.js
- package.json
This PR introduces a small reorganization of the eslint configuration (using the ```extend``` feature of the eslintrc file) and adds comments to the rules (as documentation of the motivations)
> reorganize eslint configs and add comments on rules

- karma.conf.js
This PR fixes the glob in the karma config, which includes firebug.sdk files during karma tests, to include the recently added 'lib/reps/core' files.
> Fix karma config 

- data/inspector/css/tree-editor-view.css
This PR includes a small workaround to fix the "missing close button on hover in the send packet tab" issue.
> Fix missing close button on hover in the TreeEditorView component

- data/.eslintrc
- data/inspector/components/actors-panel.js
- data/inspector/components/actors-toolbar.js
- data/inspector/components/main-tabbed-area.js
- data/inspector/components/packet.js
- data/inspector/components/packets-limit.js
- data/inspector/components/packets-summary.js
- data/inspector/components/packets-toolbar.js
- data/inspector/components/stack-frame-rep.js
- data/inspector/main.js
- data/inspector/packets-store.js
- data/inspector/rdp-inspector-window.js
this PR introduces a new small "data/inspector/rdp-inspector-window.js" module, this module is the only one in the project which uses the custom injected globals directly (the custom globals injected by this addon in the content frame where the React UI is running).
This "rdp-inspector-window" module auto-detects when the page is running over http/https or file urls and mocks the missing globals.
This change has two goals:
- restrict the use of these globals to a single module (and remove these globals from the data/.eslintrc file)
- main.html can be loaded unmodified in a tab (over http/https or file urls) and we can inspect the React UI with the React DevTools
> move special RDPi window globals into a module

- lib/inspector-actor.js
- lib/inspector-front.js
- lib/inspector-service.js
- lib/start-button.js
- lib/webide-connections-monitor.js
- package.json
- test/test-inspector-service.js
This PR updates firebug.sdk dependency (which introduces the related fixes merged directly in firebug.sdk) and fixes the remaining paths.
once merged it should fix #68
> Fix module paths (bug 912121)

- lib/inspector-window.js
This PR ensures that the inspector actors' detach method is called when the RDPi window is closed, which prevents the "Wrong State" exception described in #70 to be raised if we "close and re-open" the RDPi window on a defined debugging connection.
> detach registered inspector actors on RDPi window close

- lib/inspector-actor.js
This PR (with is connected to the firebug/firebug#16) adds the safeImport helper in the context of the injected actor to add the new devtools resource urls (introduced by https://bugzilla.mozilla.org/show_bug.cgi?id=1203159) to the supported fallback urls.
> prepare to support new devtools resource urls with fallbacks

- lib/inspector-service.js
- lib/webide-connections-monitor.js
This PR applies small changes to be able to connect the RDPInspector on any client RDP connection:
- add a new "Other" tab in the connection list window
- create a fake toolbox if the connection doesn't have its own
- list a webide connection before a real toolbox is available
> Enable rdp-inspector on any client RDP connection

- lib/transport-observer.js
Fixes issue #82: subscribe to the transport events with new names ([bug 1290599](https://bugzilla.mozilla.org/show_bug.cgi?id=1290599)).
Subscribes to both old and new names, so RDP inspector remains compatible with older versions.
@janodvarko: Any tests I need to add or update? The patched version works very well for me with the latest Nightly.
> Subscribe to the renamed transport events
